### ISSUE TITLE
Use PageRank on unthresholded w matrix

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DE-learning#53]
You'll want to take the absolute value of w's entries to remove the sign, but then you definitely don't want to threshold w before running PageRank. I'd suggest just using the w matrix directly rather than NetworkX's implementation. For example, there's an implementation you can grab from the wikipedia page.

https://en.wikipedia.org/wiki/PageRank

**Comment by Zhanzhang-2020** [comment]
I have one question about this. If we set the threshold for w and remove some insignificant interaction before calculating the pagerank, wouldn't it be better to observe which genes are important?

**Comment by aarmey** [comment]
I don't know what threshold of interactions is insignificant. Because we penalize non-zero interactions during fitting, in theory everything that is non-zero is significant.

**Comment by Zhanzhang-2020** [comment]
okay, I see
