### ISSUE TITLE
Try normalizing w to the expression level of each gene

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DE-learning#68]
Within each column of w, the magnitude of the resulting effect is proportional to the expression level of the gene it gets multiplied with. To try and normalize out this effect, I'm interested in how the results change if we divide each column of w by the expression level of its corresponding gene within the control condition.

**Comment by Zhanzhang-2020** [comment]
what if some expression values equals zero?

**Comment by aarmey** [comment]
Hmm... so if the expression level is zero, the perturbations of that column have no effect. This helped me see that there's a typo in my note above—I think we should multiply, not divide, by the expression level.

**Comment by Zhanzhang-2020** [comment]
The resulting graph after normalizing w:
![Pagerank-3](https://user-images.githubusercontent.com/65744236/92710188-25985c80-f38a-11ea-9c58-9687099c2f2c.png)
I remove genes whose control expression level equals zeros from the w matrix because I think the all-zeros columns do not fulfill the requirement of the adjacency matrix while calculating PageRank.

**Comment by Zhanzhang-2020** [comment]
Also have obtained several positive feedback loops:
![positive-feedback_loop](https://user-images.githubusercontent.com/65744236/92714033-406cd000-f38e-11ea-945c-cfc58561af3f.png)

Seems that these components are all top upstream regulators based on PageRank, and I created a subgraph containing all interactions among these components:
![positive-feedback_loop(2)](https://user-images.githubusercontent.com/65744236/92714058-482c7480-f38e-11ea-9bad-6af3d74a0f12.png)

**Comment by aarmey** [comment]
This looks fantastic! That's extremely interesting that all of the positive feedbacks are in the upstream regulators. I think we have a great hypothesis here—it looks like increasing YBX1 would suppress MITF and promote SOX10, so it could drive an intermediate steady state between MITF+ sensitive cells and SOX10+ resistance. We'll have to see what these look like in the steady states.
